import type {Metadata} from "next";

import "@fontsource/niconne";
import "@fontsource/kings";
import "@fontsource-variable/m-plus-1-code/wght.css";
import "@fontsource-variable/m-plus-1/wght.css";
import '@fontsource-variable/jetbrains-mono';
import "@fontsource-variable/nunito-sans/wdth.css";

import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import {latestUpdateYear} from "@/lib/latestUpdate";
import {countTags} from "@/lib/countTags";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ja">
    <body className={`antialiased`}>
    <Header tags={countTags}/>
    <main>
      {children}
    </main>
    <Footer latestUpdateYear={latestUpdateYear()}/>
    </body>
    </html>
  );
}
